spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bankcard?serverTimezone=UTC
    username: root
    password: xy201619
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  #  扫描的别名包
  type-aliases-package: com.personal.pojo
  mapper-locations: classpath:mapper/NUserMapper.xml